### ISSUE TITLE
Implement accelerate feature for eth based transactions

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/ethereum-kit-android#132] opened 2020-09-10 06:13 UTC
When transaction is stuck in pending state, user might need to rebroadcast it with same or higher fee.

To rebroadcast transaction use same nonce.

**Comment by esengulov** [comment] 2021-08-10 12:02
Duplicate of # https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2565

**Closed by esengulov** 2021-08-10 12:02 UTC
